### ISSUE TITLE
JSON not working if language does not match

### ISSUE THREAD

**Issue by dascgit** [dickwolff/DEGIRO-to-Ghostfolio#1] opened 2023-06-13 11:49 UTC
Which language do you expect in the CSV from degiro?
Which file can be edited so that the JSON convertion works with other languages?

**Comment by dickwolff** [comment] 2023-06-13 11:57
Hi,

Currently I'm doing checks on the Dutch language, I haven't gotten around to make it more robust so it would be language agnostic. I'm plannig to do this in the future. In the meanwhile you could try to make local changes to ìndex.ts` and try to make it work for your own language. Sale checks are at line 132, buy at line 159. 

Also note that the YAHOO finance ISIN check does not always give the expected security, like mentioned in the code with the TODO at line 84. I also had this issue with IQQH which gave me the LSE (INRG.L) variant and was not the same as then one I have (IQQH.DE). I haven't found a good solution for this yet.

**Comment by dascgit** [comment] 2023-06-13 12:55
Hi,

I have tried to edit the lines you specified but could not get it working. I am always getting "currency":"" in the JSON file.
I also haven`t found a solution to get the export from degiro in another language like english. Mine is always in German.

**Comment by Lipown** [comment] 2023-08-05 15:50
Same problem here. My exports are in CZECH language. Iam not a programmer but I can do the translation table xxx in Dutch = xxx in Czech if you can could provide me the list.

**Comment by dickwolff** [comment] 2023-08-05 16:13
I pushed some changes today eliminating the need for some more language specific search queries. I have looked at the remaining Dutch words and I believe the list below are the remaining Dutch specific words; you can translate these to Czech yourself:
- dividendbelasting -> tax on dividend/dividend tax
- verkoop -> sell 
- koop -> buy
- transactiekosten -> transaction fees

To enable me to make it completely language agnostic it would help to have an export in a foreign language. I would appreciate it if you could share a Czech export file with me. You could anonymise it if you feel more comfortable with that. As long as it contains records which enable me to differentiate buy/sell/dividend lines I could work with that. Thanks a lot!

Please note that there is a known issue in my code with the Yahoo Finance api, it will sometimes return some other stock from another exchange then you have in your Ghostfolio account. For example Yahoo Finance returns INRG.L instead of IQQH.DE (which I have). You have to manually correct these in the exported JSON.

**Comment by Lipown** [comment] 2023-08-08 07:28
Sorry for late reply! 

**tax on dividend/dividend tax** > Daň z dividendy
**buy** > Nákup
**sell** > Prodej _(have never sold so this one is guess :) )_ 
**transactiekosten** > DEGIRO Transaction and/or third party fees _(Also guess, I only found this in file and it is in English not translated Czech. Exact translation of transaction fees would be "Transakční poplatky")_

File attached:

[Account.csv](https://github.com/dickwolff/DEGIRO-to-Ghostfolio/files/12288351/Account.csv)

**Comment by dickwolff** [comment] 2023-08-08 08:25
No problem! Thanks for the file. 

I have made some changes to the converter logic so it is more language agnostic (I have removed some Dutch terms). I've attached the conversion result in my reply below. This should be really close to what your input CSV contains. If you'll validate this for me, I can push the changes to the repo. 

[ghostfolio-degiro-czech.txt](https://github.com/dickwolff/DEGIRO-to-Ghostfolio/files/12288997/ghostfolio-degiro-czech.txt)

I've validated this with my own Dutch export file and that works like a charm.

**Comment by Lipown** [comment] 2023-08-08 15:54
Could you explain what you mean by validation? You want me to load the file in ghostfolio or check visually pls? Sorry I am just IT hobbyist so I do not know exact meaning of this terminology :)

**Comment by dickwolff** [comment] 2023-08-08 15:56
Uploading to Ghostfolio would be the best way to visually check if it looks correct and the positions are also aligned with the real transactions from DEGIRO.

**Comment by Lipown** [comment] 2023-08-08 18:43
Iam getting following when I renamed ghostfolio-degiro-czech.txt to ghostfolio-degiro-czech.json and tried to import to Ghostfolio 

![obrazek](https://github.com/dickwolff/DEGIRO-to-Ghostfolio/assets/57076375/b10cf29e-be09-4b60-b784-073949c5111b)

**Comment by dickwolff** [comment] 2023-08-08 18:57
Thanks! There are some records that are empty. I'll check tomorrow what went wrong with the processing of these securities.

**Comment by dickwolff** [comment] 2023-08-08 18:59
At first glance it seems to refer to records in the CSV with `ADR/GDR Pass-Through poplatek`. Is this something Czech specific?

**Comment by dickwolff** [comment] 2023-08-08 20:28
I added "pass-trough" to the skip list and now the export is like below:

[ghostfolio-degiro-czech2.txt](https://github.com/dickwolff/DEGIRO-to-Ghostfolio/files/12295550/ghostfolio-degiro-czech2.txt)

Ghostfolio still wont import it because of the incorrect matching of `VUSA`. The Yahoo API maps it to `VUSA.L` (which is in GBp), but I think you have purchased it from a different exchange (like Euronext, Xetra or another). This is a known issue and you need to change these references yourself (replace the `VUSA.L` reference with the ticker you purchased, and also change the currency (if needed, it currently is USD).

I don't have a solution for this problem yet. No way of knowing which symbol to use with the limited information from the export. Unfortunately the ISIN query to Yahoo Finance does sometimes return an unexpected value (especially ETF's).

**Comment by Lipown** [comment] 2023-08-09 05:53
> At first glance it seems to refer to records in the CSV with `ADR/GDR Pass-Through poplatek`. Is this something Czech specific?

It seems like semi translated. _poplatek_ = fee. 

Regarding the issue of matching symbols. So I need to manually change the symbol and that's it right? :) It will be easy :) Thank you very much!

**Comment by Lipown** [comment] 2023-08-09 07:50
I tried to rewrite the symbol to VUSA.AS. I still have error:
![obrazek](https://github.com/dickwolff/DEGIRO-to-Ghostfolio/assets/57076375/7f2fb745-fe10-4583-bed3-c3e8b7cd1aab)

The issue is that the ETF is bouth in € but the divident is returned in USD. Any idea how to proceed?

**Comment by dickwolff** [comment] 2023-08-09 08:26
Is the dividend within your DEGIRO account returned in USD or EUR? If it's the latter, you could manually change the USD to EUR in the JSON file.

**Comment by Lipown** [comment] 2023-08-09 09:06
> Is the dividend within your DEGIRO account returned in USD or EUR? If it's the latter, you could manually change the USD to EUR in the JSON file.
Bought ETF by € but dividend returned in USD

![image](https://github.com/dickwolff/DEGIRO-to-Ghostfolio/assets/57076375/c8082a1a-93b1-4541-aa2a-bb2418f72d1b)

Does it affect any FX rate?

**Comment by Lipown** [comment] 2023-08-14 15:04
Hello I had finally time to test this. But after changing USD to EUR on the rows of this ETF dividents I got another error:
![obrazek](https://github.com/dickwolff/DEGIRO-to-Ghostfolio/assets/57076375/14227179-c704-4786-a10b-8e314f03530f)

Any way to load the historical FX rates pls?

**Comment by dickwolff** [comment] 2023-08-15 17:50
I believe you can do this in Ghostfolio in the admin panel and retrieve all data.

**Comment by dickwolff** [comment] 2023-09-30 11:49
I have since added a few changes making the tool also check currency before determining a match. I also moved the tool to a [generic repository](https://github.com/dickwolff/Export-To-Ghostfolio). Can you check with the new version of the tool if the problem still persists?

**Comment by dickwolff** [comment] 2023-10-13 12:48
Closing since the project has been moved to another repository

**Closed as completed by dickwolff** 2023-10-13 12:48 UTC
